import Head from 'next/head'
import React from 'react'
import '../styles/globals.css'
import store from '../app/store'
import { Provider } from 'react-redux'
// import configureStore from './configureStore'

// const store = configureStore()

function MyApp({ Component, pageProps }) {
  return(
    <Provider store={store}>
      <React.Fragment>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </React.Fragment>
    </Provider>
  )
}

export default MyApp
